apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-microservice
  template:
    metadata:
      labels:
        app: client-microservice
    spec:
      containers:
        - image: vilonja/microservice-client:2022-11-18-22-46-25
          name: client-microservice
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://surus.db.elephantsql.com:5432/fqdjhram
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: fqdjhram
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: db-password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: client-microservice
